//common

export const LOADING = "LOADING";
export const STOP_LOADING = "STOP_LOADING";

//wolapp

export const FETCH_LIST_SUCCESS = "FETCH_LIST_SUCCESS";
export const FETCH_LIST_FAILED = "FETCH_LIST_FAILED";
export const ADD_LIIKE_SUCCESS = "ADD_LIIKE_SUCCESS";
export const ADD_LIIKE_FAILED = "ADD_LIIKE_FAILED";
export const REMOVE_LIIKE_SUCCESS = "REMOVE_LIIKE_SUCCESS";
export const REMOVE_LIIKE_FAILED = "REMOVE_LIIKE_FAILED";
export const EDIT_LIIKE_SUCCESS = "EDIT_LIIKE_SUCCESS";
export const EDIT_LIIKE_FAILED = "EDIT_LIIKE_FAILED";
